### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by sethiudit** [sethiudit/cp-algos#2]
push a binary search algorithm.

**Comment by Harshdev625** [comment]
I'm on it.

**Comment by ThisisMS11** [comment]
Can you please assign this one to me?

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?

**Comment by Harshdev625** [comment]
I have already done it.

**Comment by sabhisharma-ise** [comment]
Please assign this issue!

**Comment by y-as-h** [comment]
I am intrested in solving this issue 
please assign this issue to me
